color: blue
fieldLayouts:
  60be35e0-2816-4ee4-a82f-95bae349bb25:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-05T12:01:34+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 28c98a3d-63f9-468b-9e38-98cb32e589da
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-05T12:03:20+00:00'
            elementCondition: null
            fieldUid: 57c5a440-ef0b-49ba-a878-4c745502b5e2 # Body Blocks (Complex)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddd6dac7-b8c7-4476-8bc3-cfb5fd72688d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2a9a060a-43be-45d3-86ad-bc508cae4836
        userCondition: null
handle: complexPage
hasTitleField: true
icon: memo
name: 'Page (Complex)'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
