color: null
fieldLayouts:
  d0b2b703-f738-49bf-83dc-7ef8761dfa10:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-05T11:49:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2c5a4e2c-4ae6-403b-b199-a1e6a0c1cb7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-05T11:51:27+00:00'
            elementCondition: null
            fieldUid: a4fc885f-ca7c-4977-85a6-c25ac6f4a9ad # Textarea
            handle: bodyText
            includeInCards: false
            instructions: null
            label: 'Body Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c00c0bd1-a6fc-4d94-9f4b-2e2686aad420
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d382d53a-9463-41f9-b46b-0894bc27924b
        userCondition: null
handle: textBlock
hasTitleField: true
icon: text
name: 'Text Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
