altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f03e73c3-d9a7-4703-bd4d-15b83c4a26ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-05T11:55:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c3dde0b7-15ce-4566-9a79-8bce4d7c6e3b
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2024-11-05T11:57:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: aeb9e7b2-5c8c-4ee6-81ad-ac52ac7196d1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-05T11:57:07+00:00'
            elementCondition: null
            fieldUid: a4fc885f-ca7c-4977-85a6-c25ac6f4a9ad # Textarea
            handle: caption
            includeInCards: false
            instructions: null
            label: Caption
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05bcfe60-6535-492a-b081-2d9f2807ca0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b6bdc57-0015-43f7-b36f-0c5b90cc8b1b
        userCondition: null
fs: localFiles
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: images
